=== nirdslab/dfs/xml/dfs.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- COMMON ELEMENTS (1) -->
    <!-- type definition - email -->
    <xs:simpleType name="email">
        <xs:annotation>
            <xs:documentation>e-mail address</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^.]+\..+"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- type definition - ref -->
    <xs:simpleType name="ref">
        <xs:annotation>
            <xs:documentation>reference to a pre-declared field</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:IDREF"/>
    </xs:simpleType>
    <!-- type definition - device -->
    <xs:complexType name="device">
        <xs:annotation>
            <xs:documentation>information about the recording device</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="model"
                        type="xs:string">
                <xs:annotation>
                    <xs:documentation>model of the device</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="manufacturer"
                        type="xs:string">
                <xs:annotation>
                    <xs:documentation>manufacturer of the device</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="category"
                        type="xs:string">
                <xs:annotation>
                    <xs:documentation>category of the device</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <!-- type definition - stream -->
    <xs:complexType name="stream">
        <xs:annotation>
            <xs:documentation>information about the data stream</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="name"
                        type="xs:string">
                <xs:annotation>
                    <xs:documentation>name of the data stream</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="description"
                        type="xs:string">
                <xs:annotation>
                    <xs:documentation>description of the data stream</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="unit"
                        type="xs:string">
                <xs:annotation>
                    <xs:documentation>unit of measurement</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="frequency"
                        type="xs:unsignedInt">
                <xs:annotation>
                    <xs:documentation>sampling frequency (Hz)</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="channels"
                        type="channels">
                <xs:annotation>
                    <xs:documentation>channels in the data stream</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <!-- type definition - author -->
    <xs:complexType name="author">
        <xs:annotation>
            <xs:documentation>information about the author</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="name"
                        type="xs:string">
                <xs:annotation>
                    <xs:documentation>name of the author</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="affiliation"
                        type="xs:string">
                <xs:annotation>
                    <xs:documentation>affiliation of the author</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="email"
                        type="email">
                <xs:annotation>
                    <xs:documentation>email address of the author</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <!-- type definition - dataset -->
    <xs:complexType name="dataset">
        <xs:annotation>
            <xs:documentation>information about the dataset</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="name"
                        type="xs:string">
                <xs:annotation>
                    <xs:documentation>name of the dataset</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="description"
                        type="xs:string">
                <xs:annotation>
                    <xs:documentation>description of the dataset</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="keywords"
                        type="keywords"/>
            <xs:element name="authors"
                        type="authors"/>
        </xs:sequence>
    </xs:complexType>
    <!-- type definition - file -->
    <xs:complexType name="file">
        <xs:annotation>
            <xs:documentation>information about the file</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="path"
                        type="xs:anyURI">
                <xs:annotation>
                    <xs:documentation>path to the file</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="encoding"
                        type="xs:string">
                <xs:annotation>
                    <xs:documentation>file format</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="description"
                        type="xs:string">
                <xs:annotation>
                    <xs:documentation>description of the file</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="keys"
                        type="keys">
                <xs:annotation>
                    <xs:documentation>references to each key in the file</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="checksum"
                      type="xs:hexBinary">
            <xs:annotation>
                <xs:documentation>md5 checksum of file</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <!-- type definition - field -->
    <xs:complexType name="field">
        <xs:annotation>
            <xs:documentation>information about the field</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="name"
                        type="xs:string">
                <xs:annotation>
                    <xs:documentation>name of the field</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="description"
                        type="xs:string"
                        minOccurs="0">
                <xs:annotation>
                    <xs:documentation>description of the field</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id"
                      type="xs:ID"
                      use="required">
            <xs:annotation>
                <xs:documentation>id of the field</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="dtype"
                      type="xs:string"
                      use="required">
            <xs:annotation>
                <xs:documentation>data type of field</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <!-- type definition - link -->
    <xs:complexType name="link">
        <xs:annotation>
            <xs:documentation>information about the link</xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="field"
                        type="ref"/>
        </xs:sequence>
        <xs:attribute name="type"
                      type="xs:string"
                      use="required">
            <xs:annotation>
                <xs:documentation>type of link</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <!-- type definition - meta-stream -->
    <xs:complexType name="meta-stream">
        <xs:sequence>
            <xs:element name="device"
                        type="device"/>
            <xs:element name="streams"
                        type="streams"/>
            <xs:element name="fields"
                        type="fields"
                        minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <!-- type definition - analytic-stream -->
    <xs:complexType name="analytic-stream">
        <xs:annotation>
            <xs:documentation>Metadata schema for streaming data analytics in DFS</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="info">
                <xs:annotation>
                    <xs:documentation>information about the analytics-stream</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="analytic">
                            <xs:annotation>
                                <xs:documentation>details of an analytic obtained</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="name">
                                        <xs:annotation>
                                            <xs:documentation>name of the analytic</xs:documentation>
                                        </xs:annotation>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="fields"
                        type="fields"/>
            <xs:element name="inputs">
                <xs:annotation>
                    <xs:documentation>source meta-streams used to obtain the analytics</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:sequence minOccurs="0"
                                 maxOccurs="unbounded">
                        <xs:element name="meta-stream"
                                    type="meta-stream"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="outputs"
                        type="keys"/>
        </xs:sequence>
        <xs:attribute name="checksum"
                      type="xs:hexBinary"
                      use="required">
            <xs:annotation>
                <xs:documentation>checksum of content</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <!-- type definition - meta-file -->
    <xs:complexType name="meta-file">
        <xs:annotation>
            <xs:documentation>Metadata schema for a dataset in DFS</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="dataset"
                        type="dataset"/>
            <xs:element name="fields"
                        type="fields"/>
            <xs:element name="links"
                        type="links"/>
            <xs:element name="sources">
                <xs:annotation>
                    <xs:documentation>information on all referenced data sources</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="meta-streams"
                                    type="meta-streams"/>
                        <xs:element name="files"
                                    type="files"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="checksum"
                      type="xs:hexBinary"
                      use="required">
            <xs:annotation>
                <xs:documentation>checksum of content</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="version"
                      type="xs:string"
                      use="required">
            <xs:annotation>
                <xs:documentation>semantic version</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="created"
                      type="xs:dateTime"
                      use="required">
            <xs:annotation>
                <xs:documentation>creation date/time</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="modified"
                      type="xs:dateTime"
                      use="required">
            <xs:annotation>
                <xs:documentation>last modified date/time</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <!-- COMMON ELEMENTS (2) -->
    <!-- compound type - channels -->
    <xs:complexType name="channels">
        <xs:annotation>
            <xs:documentation>information about each channel in the meta-stream</xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="channel"
                        type="ref"/>
        </xs:sequence>
    </xs:complexType>
    <!-- compound type - authors -->
    <xs:complexType name="authors">
        <xs:annotation>
            <xs:documentation>information about each author in the dataset</xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="author"
                        type="author"/>
        </xs:sequence>
    </xs:complexType>
    <!-- compound type - keywords -->
    <xs:complexType name="keywords">
        <xs:annotation>
            <xs:documentation>keywords that best describes the dataset</xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="keyword"
                        type="xs:string">
                <xs:annotation>
                    <xs:documentation>a keyword</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <!-- compound type - streams -->
    <xs:complexType name="streams">
        <xs:annotation>
            <xs:documentation>information about each data stream in the meta-stream</xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="stream"
                        type="stream"/>
        </xs:sequence>
    </xs:complexType>
    <!-- compound type - keys -->
    <xs:complexType name="keys">
        <xs:annotation>
            <xs:documentation>keys contained in a file</xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="key"
                        type="ref"/>
        </xs:sequence>
    </xs:complexType>
    <!-- compound type - fields -->
    <xs:complexType name="fields">
        <xs:annotation>
            <xs:documentation>information about all fields in the current scope</xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="field"
                        type="field"/>
        </xs:sequence>
    </xs:complexType>
    <!-- compound type - links -->
    <xs:complexType name="links">
        <xs:annotation>
            <xs:documentation>information about all links in the current scope</xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="link"
                        type="link"/>
        </xs:sequence>
    </xs:complexType>
    <!-- compound type - files -->
    <xs:complexType name="files">
        <xs:annotation>
            <xs:documentation>information about all files referenced in a meta-file</xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="file"
                        type="file"/>
        </xs:sequence>
    </xs:complexType>
    <!-- compound type - meta-streams -->
    <xs:complexType name="meta-streams">
        <xs:annotation>
            <xs:documentation>information about all meta-streams referenced in a meta-file</xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="meta-stream"
                        type="meta-stream"/>
        </xs:sequence>
    </xs:complexType>

    <!-- META STREAM -->
    <xs:element name="meta-stream">
        <xs:complexType>
            <xs:annotation>
                <xs:documentation>Metadata schema for a sensory data stream in DFS</xs:documentation>
            </xs:annotation>
            <xs:complexContent>
                <xs:extension base="meta-stream">
                    <xs:attribute name="version"
                                  type="xs:string"
                                  use="required">
                        <xs:annotation>
                            <xs:documentation>semantic version</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="checksum"
                                  type="xs:hexBinary"
                                  use="required">
                        <xs:annotation>
                            <xs:documentation>checksum of content</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <!-- META-FILE -->
    <xs:element name="meta-file"
                type="meta-file"/>

    <!-- ANALYTIC-STREAM -->
    <xs:element name="analytic-stream"
                type="analytic-stream"/>
</xs:schema>

=== nirdslab/dfs/xml/samples/02-meta-file.xml
<?xml version="1.0" encoding="UTF-8" ?>

<meta-file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../dfs.xsd">
  <info>
    <version>1.0</version>
    <created>2020-01-01T00:00:00Z</created>
    <modified>2020-01-01T00:00:00Z</modified>
    <checksum>010203040506070809000A0B0C0D0E0F</checksum>
  </info>
  <dataset>
    <name>Heart Rate of Two Participants During a Running Task</name>
    <description>
      This dataset contains recordings of heart rate of two participants during a running task.
      Recordings were obtained from an Empatica E4.
    </description>
    <keywords>
      <keyword>heart-rate</keyword>
      <keyword>running</keyword>
    </keywords>
    <authors>
      <author>
        <name>John Doe</name>
        <affiliation>Example University</affiliation>
        <email>john@example.edu</email>
      </author>
      <author>
        <name>Jane Doe</name>
        <affiliation>Example University</affiliation>
        <email>jane@example.edu</email>
      </author>
    </authors>
  </dataset>
  <fields>
    <field id="t"
           dtype="float">
      <name>timestamp</name>
      <description>Timestamp</description>
    </field>
    <field id="hr"
           dtype="float">
      <name>heart rate</name>
      <description>Heart Rate</description>
    </field>
  </fields>
  <links>
    <link type="index">
      <field>t</field>
    </link>
  </links>
  <sources>
    <meta-streams>
      <meta-stream>
        <device>
          <model>E4</model>
          <manufacturer>Empatica</manufacturer>
          <category>Wristband</category>
        </device>
        <streams>
          <stream>
            <name>timestamp</name>
            <description>timestamp at which measurements were obtained</description>
            <unit>ms</unit>
            <frequency>0</frequency>
            <channels>
              <channel>t</channel>
            </channels>
          </stream>
          <stream>
            <name>heart rate</name>
            <description>heart rate (unit - beats per minute)</description>
            <unit>bpm</unit>
            <frequency>0</frequency>
            <channels>
              <channel>hr</channel>
            </channels>
          </stream>
        </streams>
      </meta-stream>
    </meta-streams>
    <files>
      <file checksum="010203040506070809000A0B0C0D0E0F">
        <path>./p001.csv</path>
        <encoding>csv</encoding>
        <description>Recordings from Participant 1</description>
        <keys>
          <key>t</key>
          <key>hr</key>
        </keys>
      </file>
      <file checksum="F10203040506070809000A0B0C0D0E0F">
        <path>./p002.csv</path>
        <encoding>csv</encoding>
        <description>Recordings from Participant 2</description>
        <keys>
          <key>t</key>
          <key>hr</key>
        </keys>
      </file>
    </files>
  </sources>
</meta-file>

=== nirdslab/dfs/xml/samples/v1/03-analytic-stream.xml
<?xml version="1.0" encoding="UTF-8" ?>

<analytic-stream xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="https://www.cs.odu.edu/~yasith/dfs/v1/dfs.xsd">
  <info>
    <checksum>010203040506070809000A0B0C0D0E0F</checksum>
    <analytic>
      <name>de-noised heart rate</name>
    </analytic>
  </info>
  <fields>
    <field>
      <id>t</id>
      <name>timestamp</name>
      <description>Timestamp</description>
      <dtype>float</dtype>
    </field>
    <field>
      <id>hr</id>
      <name>heart rate</name>
      <description>Heart Rate</description>
      <dtype>float</dtype>
    </field>
    <field>
      <id>hr-d</id>
      <name>de-noised heart rate</name>
      <description>De-Noised Heart Rate</description>
      <dtype>float</dtype>
    </field>
  </fields>
  <inputs>
    <meta-stream>
      <device>
        <model>E4</model>
        <manufacturer>Empatica</manufacturer>
        <category>Wristband</category>
      </device>
      <streams>
        <stream>
          <name>timestamp</name>
          <description>Timestamp</description>
          <unit>ms</unit>
          <frequency>0</frequency>
          <channels>
            <channel>t</channel>
          </channels>
        </stream>
        <stream>
          <name>heart rate</name>
          <description>Heart rate (unit - beats per minute)</description>
          <unit>bpm</unit>
          <frequency>0</frequency>
          <channels>
            <channel>hr</channel>
          </channels>
        </stream>
      </streams>
    </meta-stream>
  </inputs>
  <outputs>
    <key>hr-d</key>
  </outputs>
</analytic-stream>

=== nirdslab/dfs/xml/samples/01-meta-stream.xml
<?xml version="1.0" encoding="UTF-8" ?>

<meta-stream xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="../dfs.xsd">
  <info>
    <version>1.0.0</version>
    <checksum>010203040506070809000A0B0C0D0E0F</checksum>
  </info>
  <device>
    <model>E4</model>
    <manufacturer>Empatica</manufacturer>
    <category>Wristband</category>
  </device>
  <fields>
    <field id="acc_x"
           dtype="float">
      <name>x - acceleration</name>
      <description>Acceleration in the X axis</description>
    </field>
    <field id="acc_y"
           dtype="float">
      <name>y - acceleration</name>
      <description>Acceleration in the Y axis</description>
    </field>
    <field id="acc_z"
           dtype="float">
      <name>z - acceleration</name>
      <description>Acceleration in the Z axis</description>
    </field>
    <field id="bvp"
           dtype="float">
      <name>blood volume pulse</name>
      <description>Blood Volume Pulse</description>
    </field>
    <field id="gsr"
           dtype="float">
      <name>galvanic skin response</name>
      <description>Galvanic Skin Response</description>
    </field>
    <field id="ibi"
           dtype="float">
      <name>inter beat interval</name>
      <description>The interval between two consecutive heartbeats</description>
    </field>
    <field id="hr"
           dtype="float">
      <name>heart rate</name>
      <description>Heart Rate</description>
    </field>
    <field id="tmp"
           dtype="float">
      <name>skin temperature</name>
      <description>Skin Temperature on the Wrist</description>
    </field>
    <field id="bat"
           dtype="float">
      <name>battery level</name>
      <description>Battery Level of the Device</description>
    </field>
    <field id="tag"
           dtype="float">
      <name>tag</name>
      <description>Press of the Tag Button</description>
    </field>
  </fields>
  <streams>
    <stream>
      <name>acceleration</name>
      <description>3-axis acceleration (unit - gravity)</description>
      <unit>g</unit>
      <frequency>32</frequency>
      <channels>
        <channel>acc_x</channel>
        <channel>acc_y</channel>
        <channel>acc_z</channel>
      </channels>
    </stream>
    <stream>
      <name>blood volume pulse</name>
      <description>Blood Volume Pulse (unit - lumen)</description>
      <unit>lm</unit>
      <frequency>64</frequency>
      <channels>
        <channel>bvp</channel>
      </channels>
    </stream>
    <stream>
      <name>galvanic skin response</name>
      <description>Galvanic Skin Response (unit - micro siemens)</description>
      <unit>Î¼S</unit>
      <frequency>0</frequency>
      <channels>
        <channel>gsr</channel>
      </channels>
    </stream>
    <stream>
      <name>inter-beat interval</name>
      <description>Inter-Beat Interval (unit - seconds)</description>
      <unit>s</unit>
      <frequency>0</frequency>
      <channels>
        <channel>ibi</channel>
      </channels>
    </stream>
    <stream>
      <name>heart rate</name>
      <description>Heart rate (unit - beats per minute)</description>
      <unit>bpm</unit>
      <frequency>0</frequency>
      <channels>
        <channel>hr</channel>
      </channels>
    </stream>
    <stream>
      <name>skin temperature</name>
      <description>Skin Temperature (unit - celsius)</description>
      <unit>c</unit>
      <frequency>0</frequency>
      <channels>
        <channel>tmp</channel>
      </channels>
    </stream>
    <stream>
      <name>battery level</name>
      <description>Device Battery (unit - percent)</description>
      <unit>%</unit>
      <frequency>0</frequency>
      <channels>
        <channel>bat</channel>
      </channels>
    </stream>
    <stream>
      <name>tag</name>
      <description>Tag recorded upon button press</description>
      <unit/>
      <frequency>0</frequency>
      <channels>
        <channel>tag</channel>
      </channels>
    </stream>
  </streams>
</meta-stream>
